package com.grimmslaw.pokemon.abilities;

public enum Ability {

    // TODO:
    NONE, GUTS, ADAPTABILITY, INFILTRATOR, FLUFFY, FILTER, FRIEND_GUARD, MULTISCALE, PRISM_ARMOR, SHADOW_SHIELD, SNIPER,
    SOLID_ROCK, TINTED_LENS

}
